Grandmarket/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('market.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),

]

market/urls.py
from django.urls import path
from . import views


app_name = 'market'
urlpatterns = [
    path('', views.home, name='home'),
    path('Grandmarket/market', views.market, name='market'),
    path('Grandmarket/add-item', views.add, name='add-item'),
    path('Grandmarket/cart', views.cart, name='cart'),
    path('Grandmarket/order', views.order, name='orders'),
    path('Grandmarket/detail', views.detail, name='detail'),
    path('Grandmarket/profile', views.profile, name='profile'),
    path('Grandmarket/store', views.store, name='store'),
    path('Grandmarket/search', views.search, name='search results'),
    path('Grandmarket/stores', views.stores, name='stores'),
    path('Grandmarket/sign-in', views.signin, name='sign-in'),
    path('Grandmarket/sign-up', views.signup, name='sign-up'),
    path('Grandmarket/favorites', views.favorites, name='favorites'),
    path('Grandmarket/about', views.about, name='about'),
]

market/models.py
from django.db import models

# Create your models here.

market/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    return render(request, 'market/home.html')


def market(request):
    return render(request, 'market/market.html')


def add(request):
    return render(request, 'market/add.html')


def cart(request):
    return render(request, 'market/cart.html')


def order(request):
    return render(request, 'market/order.html')


def detail(request):
    return render(request, 'market/page-detail.html')


def profile(request):
    return render(request, 'market/profile.html')


def signup(request):
    return render(request, 'market/sign-up.html')


def signin(request):
    return render(request, 'market/sign-in.html')


def store(request):
    return render(request, 'market/store_front.html')


def search(request):
    return render(request, 'market/search.html')


def stores(request):
    return render(request, 'market/stores.html')


def new_store(request):
    return render(request, 'market/storeform.html')


def favorites(request):
    return render(request, 'market/favorites.html')


def about(request):
    return render(request, 'market/about.html')

market/templates/market/about.html
<!DOCTYPE html>
<html lang="en">
{% load static %}


<body class="bg-green-200">

	{% block content %}
	{% include 'market/base.html' %}

			<section class="flex flex-row font-serif justify-evenly rounded text-center">
                <div class="px-8 bg-black text-green-500">
                    <h1>Why use GrandMarket Ja?</h1>
                    <p>Because it is a market place designed for both hustlers and entrepreneurs.
                        We are a social market place meaning we cater for 1 time sells who dont have a business just hustling some good as well as entrepreneurs with stocks of goods or services they want to sell</p>

                </div>
                <div class="px-8 bg-green-900 text-yellow-500">
                    <h1>How to use GrandMarket Ja?</h1>
                    <p>You can scroll through the various stores and see the market for free without signing up but the best experience comes from being a member</p>
                </div>
                <div class="px-8 bg-yellow-500 text-black">
                    <h1>How to use GrandMarket Ja?</h1>
                    <p></p>
                </div>
            </section>



	{% endblock content %}


</body>
</html>

market/templates/market/add.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

	<script>
		function open_sidebar(){
		  document.getElementById('sidebar').classList.remove('-left-full');
		  document.getElementById('backdrop').classList.remove('hidden');
		}
		function hide_sidebar(){
		  document.getElementById('sidebar').classList.add('-left-full');
		  document.getElementById('backdrop').classList.add('hidden');
		}
  </script>

{% include 'market/base.html' %}
	{% block content %}
		<body class="bg-gray-100 text-gray-600">



				<section class="container max-w-3xl p-6 mx-auto">

					<article class="bg-white rounded shadow-sm border border-gray-200 p-4 lg:p-6 my-5">

					  <h2 class="mb-3 text-xl md:text-2xl font-semibold text-black">
						Create new item
					  </h2>

					  <form>

						<div class="mb-4">
						  <label class="block mb-1"> Name of item </label>
						  <input type="text" class="appearance-none border border-gray-200 bg-gray-100 rounded-md py-2 px-3 hover:border-gray-400 focus:outline-none focus:border-gray-400 w-full" placeholder="Type here" />
						</div>

						<div class="mb-4">
						  <label class="block mb-1"> Description </label>
						  <textarea rows="4" class="appearance-none border border-gray-200 bg-gray-100 rounded-md py-2 px-3 hover:border-gray-400 focus:outline-none focus:border-gray-400 w-full" placeholder="Type here" ></textarea>
						</div>

						<div class="mb-4">
						  <label class="block mb-1"> Image upload </label>
						  <input type="file" class="w-72" placeholder="Type here" />
						</div>

						<div class="mb-4">
						  <label class="block mb-1"> Tags input </label>
						  <input type="text" class="appearance-none border border-gray-200 bg-gray-100 rounded-md py-2 px-3 hover:border-gray-400 focus:outline-none focus:border-gray-400 w-full" placeholder="Tag, Tag,..." />
						</div>

						<div class="grid md:grid-cols-2 gap-x-2">
							<div class="mb-4">
								<label class="block mb-1"> Category </label>
								<div class="relative">
								  <select class="block appearance-none border border-gray-200 bg-gray-100 rounded-md py-2 px-3 hover:border-gray-400 focus:outline-none focus:border-gray-400 w-full">
									<option> Uncategorized </option>
									<option> Automibiles </option>
									<option> Clothings </option>
									<option> Home items </option>
								  </select>
								  <i class="absolute inset-y-0 right-0 p-2 text-gray-400">
									<svg width="22" height="22" class="fill-current" viewBox="0 0 20 20"><path d="M7 10l5 5 5-5H7z"></path></svg>
								  </i>
								</div>
							</div>
							<div class="mb-4">
								<label class="block mb-1"> Subcategory </label>
								<div class="relative">
									<select class="block appearance-none border border-gray-200 bg-gray-100 rounded-md py-2 px-3 hover:border-gray-400 focus:outline-none focus:border-gray-400 w-full">
									  <option> Select directory </option>
									  <option> Modern cars</option>
									  <option> Electric cars </option>
									  <option> Motorcycles</option>
									</select>
									<i class="absolute inset-y-0 right-0 p-2 text-gray-400">
									  <svg width="22" height="22" class="fill-current" viewBox="0 0 20 20"><path d="M7 10l5 5 5-5H7z"></path></svg>
									</i>
								</div>
							</div>
						</div> <!-- grid -->

						<div class="mb-4">
							<label class="block mb-1"> Price  </label>
							<div class="grid grid-cols-3 gap-x-2 md:w-1/2">
							  <div class="col-span-2">
								  <input type="text" class="appearance-none border border-gray-200 bg-gray-100 rounded-md py-2 px-3 hover:border-gray-400 focus:outline-none focus:border-gray-400 w-full" placeholder="0.00" />
							  </div>
							  <div>
								  <select class="block appearance-none border border-gray-200 bg-gray-100 rounded-md py-2 px-3 hover:border-gray-400 focus:outline-none focus:border-gray-400 w-full" placeholder="Select one option">
									<option> USD</option>
									<option> EUR </option>
									<option> JMD</option>
								  </select>
							  </div>
							</div> <!-- flex grid -->
						</div>

						<label class="flex items-center w-max my-4">
						  <input checked name="" type="checkbox" class="h-4 w-4">
						  <span class="ml-2 inline-block text-gray-500"> Publish item now </span>
						</label>

						<button type="submit" class="my-2 px-4 py-2 text-center inline-block text-white bg-blue-600 border border-transparent rounded-md hover:bg-blue-700"> Submit item </button>

						<a href="#" class="px-4 py-2 inline-block text-gray-700 bg-white shadow-sm border border-gray-200 rounded-md hover:bg-gray-100 hover:text-blue-600"> Cancel </a>

					  </form>

					</article>


				</section> <!-- container -->
			  </main>
			</div>
		</body>

	{% endblock content %}



</html>

market/templates/market/base.html
<!DOCTYPE html>
{% load static tailwind_tags %}

<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta name="description" content="Type some info" />
		<meta name="author" content="Type name" />
		{% tailwind_css %}
		<title>Grandmarket Ja</title>

		<!-- Tailwind css -->
		<link href="css/tailwind.min.css" rel="stylesheet" />

		<!-- Font awesome 5 -->
		<link href="{% static 'market/fonts/fontawesome/css/all.min.css' %}"  rel="stylesheet" />

		<script>
			function open(){
			  document.getElementById('menu').classList.remove('hidden');
			}
			function hide(){
			  document.getElementById('sidebar').classList.add('-left-full');
			  document.getElementById('backdrop').classList.add('hidden');
			}
		</script>
	</head>


            	<!--  COMPONENT: HEADER -->
	<header class="bg-green-600 py-3 border-b">
		<div class="container max-w-screen-xl mx-auto px-4">
			<div class="flex flex-wrap items-center">
				<!-- Brand -->
				<div class="flex-shrink-0 mr-5">
					<a href="{% url 'market:home' %}"> <img src="{% static 'market/images/logo.svg' %}" height="38" alt="Brand" /> </a>
				</div>
				<!-- Brand .//end -->

				<!-- Search -->
				<div class="flex flex-nowrap items-center w-full order-last md:order-none mt-5 md:mt-0 md:w-2/4 lg:w-2/4">
					<input class="flex-grow appearance-none border border-gray-200 bg-gray-100 rounded-md mr-2 py-2 px-3 hover:border-gray-400 focus:outline-none focus:border-gray-400" type="text" placeholder="Search">
					<button type="button" class="px-4 py-2 inline-block text-white border border-transparent bg-yellow-400 rounded-md hover:bg-blue-700">
						<i class="fa fa-search"></i>
					</button>
				</div>
				<!-- Search .//end -->

				<!-- Actions -->
				<div class="flex items-center space-x-2 ml-auto">
					{% if request.user.is_authenticated %}
						<a class="px-3 py-2 inline-block text-center text-gray-700 bg-white shadow-sm border border-gray-200 rounded-md hover:bg-gray-100 hover:border-gray-300" href="{% url 'market:sign-out' %}">
							<i class="text-gray-400 w-5 fa fa-user"></i>
							<span class="hidden lg:inline ml-1">Sign out</span>
						</a>
					{% else%}
						<a class="px-3 py-2 inline-block text-center text-gray-700 bg-white shadow-sm border border-gray-200 rounded-md hover:bg-gray-100 hover:border-gray-300" href="{% url 'market:sign-in' %}">
							<i class="text-gray-400 w-5 fa fa-user"></i>
							<span class="hidden lg:inline ml-1">Sign in</span>
						</a>
					{% endif %}

					<a class="px-3 py-2 inline-block text-center text-gray-700 bg-white shadow-sm border border-gray-200 rounded-md hover:bg-gray-100 hover:border-gray-300" href="{% url 'market:store' %}">
						<i class="text-gray-400 w-5 fa fa-heart"></i>
						<span class="hidden lg:inline ml-1">My Store</span>
					</a>

					<a class="px-3 py-2 inline-block text-center text-gray-700 bg-white shadow-sm border border-gray-200 rounded-md hover:bg-gray-100 hover:border-gray-300" href="{% url 'market:cart' %}">
						<i class="text-gray-400 w-5 fa fa-shopping-cart"></i>
						<span class="hidden lg:inline ml-1">My cart</span>
					</a>
					<div class="flex items-center md:order-2">
					  <button type="button" class="flex mr-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" type="button" data-dropdown-toggle="dropdown">
						<span class="sr-only">Open user menu</span>
						<img class="w-8 h-8 rounded-full" src="{% static 'market/images/prof.png' %}" alt="user photo">
					  </button>
					  <!-- Dropdown menu -->
					  <div class="hidden z-50 my-4 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600" id="dropdown">
						<div class="py-3 px-4">
						  <span class="block text-sm text-gray-900 dark:text-white">Bonnie Green</span>
						  <span class="block text-sm font-medium text-gray-500 truncate dark:text-gray-400">name@flowbite.com</span>
						</div>
						<ul class="py-1" aria-labelledby="dropdown">
						  <li>
							<a href="#" class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Dashboard</a>
						  </li>
						  <li>
							<a href="#" class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Settings</a>
						  </li>
						  <li>
							<a href="#" class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Earnings</a>
						  </li>
						  <li>
							<a href="#" class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Sign out</a>
						  </li>
						</ul>
					  </div>
					</div>
				<!-- Actions .//end -->

				<!-- mobile-only -->
				<div class="lg:hidden ml-2">
					<button type="button"  class="bg-white p-3 inline-flex items-center rounded-md text-black hover:bg-gray-200 hover:text-gray-800 border border-transparent">
						<span class="sr-only">Open menu</span>
						<i class="fa fa-bars fa-lg"></i>
					</button>
				</div>
				<!-- mobile-only //end  -->

			</div> <!-- flex grid //end -->
		</div> <!-- container //end -->
	</header>
	<nav class="border-b bg-gray-100">
		<div class="container max-w-screen-xl mx-auto px-4">
			<!-- Bottom -->
			<div id="menu" class="hidden lg:flex flex-1 items-center py-1">
				<a class="px-3 py-2 rounded-md hover:bg-gray-200" href="{% url 'market:home' %}"> Category </a>
				<a class="px-3 py-2 rounded-md hover:bg-gray-200" href="{% url 'market:market' %}"> Market </a>
				<a class="px-3 py-2 rounded-md hover:bg-gray-200" href="{% url 'market:stores' %}"> Stores </a>
				<a class="px-3 py-2 rounded-md hover:bg-gray-200" href="{% url 'market:favorites' %}"> Favorites </a>
				<a class="px-3 py-2 rounded-md hover:bg-gray-200" href="{% url 'market:about' %}"> About </a>
			</div>
			<!-- Bottom //end -->
		</div> <!-- container //end -->
	</nav>
	<!--  COMPONENT: HEADER //END -->

	{% block content %}
	<!-- Content goes here -->

	{% endblock content %}

	<script>
		function myFunction() {
	   var element = document.getElementById("myDIV");
	   element.classList.toggle("mystyle");
	}
	</script>
	<script src="https://unpkg.com/flowbite@1.4.5/dist/flowbite.js"></script>
</html>

market/templates/market/cart.html
<!DOCTYPE html>
<html lang="en">
{% load static %}


<body>

	{% block content %}
	{% include 'market/base.html' %}

	<!--  PAGE HEADER -->
	<section class="py-5 sm:py-7 bg-blue-100">
		<div class="container max-w-screen-xl mx-auto px-4">
			<!-- breadcrumbs start -->
			<h2 class="text-3xl font-semibold mb-2">Shopping cart</h2>

		</div><!-- /.container -->
	</section>
	<!--  PAGE HEADER .//END  -->

	<section class="py-10">
		<div class="container max-w-screen-xl mx-auto px-4">

<div class="flex flex-col md:flex-row gap-4">
	<main  class="md:w-3/4">

		<article class="border border-gray-200 bg-white shadow-sm rounded mb-5 p-3 lg:p-5">

			<!-- item-cart -->
			<div class="flex flex-wrap lg:flex-row gap-5  mb-4">
				<div class="w-full lg:w-2/5 xl:w-2/4">
					<figure class="flex leading-5">
						<div>
							<div class="block w-16 h-16 rounded border border-gray-200 overflow-hidden">
								<img src="images/items/1.jpg" alt="Title">
							</div>
						</div>
						<figcaption  class="ml-3">
							<p><a href="#" class="hover:text-blue-600">Modern Product Name Goes Here as demo </a></p>
							<p class="mt-1 text-gray-400"> Color: Yellow, Type: Jeans </p>
						</figcaption>
					</figure>
				</div>
				<div class="">
					<!-- selection -->
					<div class="w-24 relative">
				    <select class="block appearance-none border border-gray-200 bg-gray-100 rounded-md py-2 px-3 hover:border-gray-400 focus:outline-none focus:border-gray-400 w-full">
				        <option>1</option>
						<option>2</option>
						<option>3</option>
			      	</select>
				    <i class="absolute inset-y-0 right-0 p-2 text-gray-400">
				        <svg width="22" height="22" class="fill-current" viewBox="0 0 20 20"><path d="M7 10l5 5 5-5H7z"></path></svg>
				    </i>
				   </div>
				   <!-- selection .//end -->
				</div>
				<div>
					<div class="leading-5">
						<p class="font-semibold not-italic">$1156.00</p>
						<small class="text-gray-400"> $460.00 / per item </small>
					</div>
				</div>
				<div class="flex-auto">
					<div class="float-right">
						<a href="#" class="px-3 py-2 inline-block text-blue-600 bg-blue-100 border border-transparent rounded-md hover:bg-blue-200"> <i class="fa fa-heart"></i> </a>
						<a class="px-4 py-2 inline-block text-red-600 bg-white shadow-sm border border-gray-200 rounded-md hover:bg-gray-100" href="#">  Remove </a>
					</div>
				</div>
			</div> <!-- item-cart end// -->

			<hr class="my-4">

			<!-- item-cart -->
			<div class="flex flex-wrap lg:flex-row gap-5 mb-4">
				<div class="w-full lg:w-2/5 xl:w-2/4">
					<figure class="flex leading-5">
						<div>
							<div class="block w-16 h-16 rounded border border-gray-200 overflow-hidden">
								<img src="images/items/2.jpg" alt="Title">
							</div>
						</div>
						<figcaption  class="ml-3">
							<p><a href="#" class="hover:text-blue-600">Travel Bag Jeans Blue Color Modern</a></p>
							<p class="mt-1 text-gray-400"> Color: Yellow, Type: Jeans </p>
						</figcaption>
					</figure>
				</div>
				<div class="">
					<!-- selection -->
					<div class="w-24 relative">
				    <select class="block appearance-none border border-gray-200 bg-gray-100 rounded-md py-2 px-3 hover:border-gray-400 focus:outline-none focus:border-gray-400 w-full">
				        <option>1</option>
						<option selected>2</option>
						<option>3</option>
			      	</select>
				    <i class="absolute inset-y-0 right-0 p-2 text-gray-400">
				        <svg width="22" height="22" class="fill-current" viewBox="0 0 20 20"><path d="M7 10l5 5 5-5H7z"></path></svg>
				    </i>
				   </div>
				   <!-- selection .//end -->
				</div>
				<div>
					<div class="leading-5">
						<p class="font-semibold not-italic">$92.00</p>
						<small class="text-gray-400"> $34.00 / per item </small>
					</div>
				</div>
				<div class="flex-auto">
					<div class="float-right">
						<a href="#" class="px-3 py-2 inline-block text-blue-600 bg-blue-100 border border-transparent rounded-md hover:bg-blue-200"> <i class="fa fa-heart"></i> </a>
						<a class="px-4 py-2 inline-block text-red-600 bg-white shadow-sm border border-gray-200 rounded-md hover:bg-gray-100" href="#">  Remove </a>
					</div>
				</div>
			</div> <!-- item-cart end// -->

			<hr class="my-4">

			<!-- item-cart -->
			<div class="flex flex-wrap lg:flex-row gap-5 mb-4">
				<div class="w-full lg:w-2/5 xl:w-2/4">
					<figure class="flex leading-5">
						<div>
							<div class="block w-16 h-16 rounded border border-gray-200 overflow-hidden">
								<img src="images/items/3.jpg" alt="Title">
							</div>
						</div>
						<figcaption  class="ml-3">
							<p><a href="#" class="hover:text-blue-600">Great product name</a></p>
							<p class="mt-1 text-gray-400"> Color: Blue, Type: Original </p>
						</figcaption>
					</figure>
				</div>
				<div class="">
					<!-- selection -->
					<div class="w-24 relative">
				    <select class="block appearance-none border border-gray-200 bg-gray-100 rounded-md py-2 px-3 hover:border-gray-400 focus:outline-none focus:border-gray-400 w-full">
				        <option>1</option>
						<option>2</option>
						<option>3</option>
			      	</select>
				    <i class="absolute inset-y-0 right-0 p-2 text-gray-400">
				        <svg width="22" height="22" class="fill-current" viewBox="0 0 20 20"><path d="M7 10l5 5 5-5H7z"></path></svg>
				    </i>
				   </div>
				   <!-- selection .//end -->
				</div>
				<div>
					<div class="leading-5">
						<p class="font-semibold not-italic">$980.00</p>
						<small class="text-gray-400"> $120.00 / per item </small>
					</div>
				</div>
				<div class="flex-auto">
					<div class="float-right">
						<a href="#" class="px-3 py-2 inline-block text-blue-600 bg-blue-100 border border-transparent rounded-md hover:bg-blue-200"> <i class="fa fa-heart"></i> </a>
						<a class="px-4 py-2 inline-block text-red-600 bg-white shadow-sm border border-gray-200 rounded-md hover:bg-gray-100" href="#">  Remove </a>
					</div>
				</div>
			</div> <!-- item-cart end// -->

			<hr class="my-4">

			<h6 class="font-bold">Free Delivery within 1-2 weeks</h6>
			<p class="text-gray-400">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip</p>

		</article> <!-- card end.// -->

	</main>
	<aside class="md:w-1/4">

		<article class="border border-gray-200 bg-white shadow-sm rounded mb-5 p-3 lg:p-5">

			<ul class="mb-5">
				<li class="flex justify-between text-gray-600  mb-1">
					<span>Total price:</span>
					<span>$245.97</span>
				</li>
				<li class="flex justify-between text-gray-600  mb-1">
					<span>Discount:</span>
					<span class="text-green-500">- $60.00</span>
				</li>
				<li class="flex justify-between text-gray-600  mb-1">
					<span>TAX:</span>
					<span>$14.00</span>
				</li>
				<li class="text-lg font-bold border-t flex justify-between mt-3 pt-3">
					<span>Total price:</span>
					<span>$420.00</span>
				</li>
			</ul>

			<a class="px-4 py-3 mb-2 inline-block text-lg w-full text-center font-medium text-white bg-green-600 border border-transparent rounded-md hover:bg-green-700" href="#"> Checkout </a>

			<a class="px-4 py-3 inline-block text-lg w-full text-center font-medium text-green-600 bg-white shadow-sm border border-gray-200 rounded-md hover:bg-gray-100" href="#"> Back to shop </a>

		</article> <!-- card end.// -->

	</aside> <!-- col.// -->
</div> <!-- grid.// -->

		</div>
	</section>



	<!-- SECTION-RECOMMENDED -->
	<section class="pt-10 pb-20 bg-gray-100">
		<div class="container max-w-screen-xl mx-auto px-4">
			<h2 class="text-2xl font-semibold mb-8">Recommended products</h2>

			<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
				<div>
					<!-- COMPONENT: PRODUCT CARD -->
					<article class="shadow-sm rounded bg-white border border-gray-200">
						<a href="#" class="relative block p-1">
							<img src="images/items/14.jpg" class="mx-auto w-auto" style="height: 250px" height="250" alt="Product title here">
						</a>
						<div class="p-4 border-t border-t-gray-200">
							<h6>
								<a href="#" class="text-gray-600 hover:text-blue-500">Product name goes here</a>
							</h6>
							<p class="text-sm text-gray-400">Sizes: S, M, XL</p>
							<span class="font-semibold">$76.00</span>
						</div>
					</article>
					<!-- COMPONENT: PRODUCT CARD //END -->
				</div>
				<div>
					<!-- COMPONENT: PRODUCT CARD -->
					<article class="shadow-sm rounded bg-white border border-gray-200">
						<a href="#" class="relative block p-1">
							<img src="images/items/12.jpg" class="mx-auto w-auto" style="height: 250px" height="250" alt="Product title here">
						</a>
						<div class="p-4 border-t border-t-gray-200">
							<h6>
								<a href="#" class="text-gray-600 hover:text-blue-500">Product name goes here</a>
							</h6>
							<p class="text-sm text-gray-400">Sizes: S, M, XL</p>
							<span class="font-semibold">$76.00</span>
						</div>
					</article>
					<!-- COMPONENT: PRODUCT CARD //END -->
				</div>
				<div>
					<!-- COMPONENT: PRODUCT CARD -->
					<article class="shadow-sm rounded bg-white border border-gray-200">
						<a href="#" class="relative block p-1">
							<img src="images/items/9.jpg" class="mx-auto w-auto" style="height: 250px" height="250" alt="Product title here">
						</a>
						<div class="p-4 border-t border-t-gray-200">
							<h6>
								<a href="#" class="text-gray-600 hover:text-blue-500">Product name goes here</a>
							</h6>
							<p class="text-sm text-gray-400">Sizes: S, M, XL</p>
							<span class="font-semibold">$76.00</span>
						</div>
					</article>
					<!-- COMPONENT: PRODUCT CARD //END -->
				</div>
				<div>
					<!-- COMPONENT: PRODUCT CARD -->
					<article class="shadow-sm rounded bg-white border border-gray-200">
						<a href="#" class="relative block p-1">
							<img src="images/items/8.jpg" class="mx-auto w-auto" style="height: 250px" height="250" alt="Product title here">
						</a>
						<div class="p-4 border-t border-t-gray-200">
							<h6>
								<a href="#" class="text-gray-600 hover:text-blue-500">Product name goes here</a>
							</h6>
							<p class="text-sm text-gray-400">Sizes: S, M, XL</p>
							<span class="font-semibold">$76.00</span>
						</div>
					</article>
					<!-- COMPONENT: PRODUCT CARD //END -->
				</div>
			</div> <!-- grid .// -->
		</div>
	</section>
	<!--  SECTION-RECOMMENDED  //END -->

	<footer class="py-6 bg-gray-200">
		<p class="text-center"><a href="https://tailwind-ecommerce.com">Tailwind ecommerce</a></p>
	</footer>

	{% endblock content %}


</body>
</html>

market/templates/market/favorites.html
<!DOCTYPE html>
<html lang="en">
{% load static %}


<body class="bg-green-200">

	{% block content %}
	{% include 'market/base.html' %}

			<h3>No favorites found...</h3>

	{% endblock content %}


</body>
</html>

market/templates/market/store_front.html
<!DOCTYPE html>
<html lang="en">
{% load static %}


<body class="bg-green-200 overflow-scroll">

	{% block content %}
	{% include 'market/base.html' %}
	<div class="flex flex-col">
		<div class="">
			<h1 class="text-5xl text-center font-semibold mt-5">Welcome to Apple kings</h1>
			<h5 class="text-center text-2xl mt-4">Shop authentic Apple products with AppleKings</h5>
			<div class="flex justify-center text-center ">
				<p>Owned by: </p>
			</div>
			<div class="">
				<h1 class="text-center"> Best sellers</h1>
			</div>

		</div>
	</div>


	{% endblock content %}


</body>
</html>